import type { Metadata } from "next";
import {
  Inter,
  Unna,
  Cormorant_Infant,
  Montserrat,
  Anton_SC,
} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const antonSc = Anton_SC({
  variable: "--font-anton-sc",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${montserrat.variable} ${antonSc.variable} antialiased min-w-[350px]`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
